version: 2.1

executors:
  node-executor:
    docker:
      - image: cypress/base:14

jobs:
  cypress-run:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Node.js dependencies
          command: npm install
      - run:
          name: Install Cypress
          command: npm install cypress --save-dev
      - run:
          name: Install Cypress Xpath
          command: npm install -D cypress-xpath
      - run:
          name: Install Chrome
          command: |
            apt-get update
            apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
            sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            apt-get update
            apt-get install -y google-chrome-stable
      - run:
          name: Run Cypress tests
          command: npx cypress run --browser chrome --headless --env ENVIRONMENT=pdn
      - store_artifacts:
          path: cypress/screenshots
          destination: screenshots
      - store_test_results:
          path: cypress/results
          destination: results

workflows:
  version: 2
  cypress:
    jobs:
      - cypress-run
